### PR TITLE
Update orgmode.lua

### PR DESCRIPTION
**Pull request by Shipley1105**
Add `org_capture_template`

### CODE REVIEW

**Comment by Martins3** [comment]
Thank you, I'll look into it

**Comment by Martins3** [comment]
Can you add a document about how to use it in nvim.md, I'm not so familiar with orgmode now and switch to https://todoist.com years ago.

**Comment by Martins3** [comment]
@Shipley1105 is this thread still alive?

**Comment by Shipley1105** [comment]
After these days trial, orgmode is well suited for offline senario.
I am not familiar your Doc layout, Could you help complete the document?
Here is the user guide:
Trigger *orgmode capture* using `<space>oc`, choose which template you want.
Show agenda view using `<space>oa` and you can change to week view/month view/year view using `vw`/`vm`/``vy`.
For more detail you can read [this](https://github.com/nvim-orgmode/orgmode/blob/master/DOCS.md#agenda-mappings)

**Pull request merged**
